spring:
  profiles:
    active: dev

---
server:
  port: 8761

spring:
  profiles: dev
  application:
    name: server-eureka


eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  server:
    enable-self-preservation: false # 禁用自我保护机制*****************

---

server:
  port: 8888

spring:
  profiles: prod
  application:
    name: config-server


eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  server:
    enable-self-preservation: true # 禁用自我保护机制*****************
