
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    #通过eureka.client.registerWithEureka：false和fetchRegistry：false来表明自己是一个eureka server.
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: server-eureka


#spring:
#  profiles:
#    active: dev
#
#---
#server:
#  port: 8761
#
#spring:
#  profiles: dev
#  application:
#    name: config-eureka
#
#
#eureka:
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#
#  server:
#    enable-self-preservation: false # 禁用自我保护机制*****************
#
#---
#
#server:
#  port: 8761
#
#spring:
#  profiles: prod
#  application:
#    name: config-eureka
#
#
#eureka:
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#
#  server:
#    enable-self-preservation: true # 禁用自我保护机制*****************
