eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/       #指定服务注册中心

server:
  port: 8769

spring:
  application:
    name: service-zuul

  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888/

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: com.zr.service-ribbon
    api-b:
      path: /api-b/**
      serviceId: com.zr.service-feign